#-----
version: '3'
services:
    web:
        #dockerfile: Dockerfile
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
            - ./upload:/app/upload
        depends_on:
            - redis

    redis:
        image: redis


